name: Continuous integration
on:
  push:
    branches:
      - image
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive --force
      - run: ./build.sh
