name: Continuous integration
on:
  push:
    branches:
      - image
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive --force
      - run: docker build .
